version: "3.7"
services:
  mysql:
    image: mysql:8-oracle
    restart: always
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=watchman
      - MYSQL_USER=watchman
      - MYSQL_PASSWORD=watchman
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - docker-nginx_intranet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    tmpfs: # Run this mysql in memory as its used for testing
      - /var/lib/mysql

  watchman:
    image: ${CONTAINER_REPO}/watchman-prd:latest
    environment:
      - DATABASE_TYPE=mysql
      - MYSQL_ADDRESS=tcp(mysql:3306)
      - MYSQL_DATABASE=watchman
      - MYSQL_USER=watchman
      - MYSQL_PASSWORD=watchman
      - MYSQL_ROOT_PASSWORD=root
    env_file:
      - .env
    networks:
      - docker-nginx_intranet
    expose:
      - "8084"
      - "9094"

networks:
  docker-nginx_intranet:
    external: true
