version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 8084:443
    restart: always
    networks:
      - intranet    
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    networks:
      - intranet    
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
      
  mysql:
    image: mysql:8-oracle
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=watchman
      - MYSQL_USER=watchman
      - MYSQL_PASSWORD=watchman
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - intranet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    tmpfs: # Run this mysql in memory as its used for testing
      - /var/lib/mysql

  watchman:
    build: .
    environment:
      - DATABASE_TYPE=mysql
      - MYSQL_ADDRESS=tcp(mysql:3306)
      - MYSQL_DATABASE=watchman
      - MYSQL_USER=watchman
      - MYSQL_PASSWORD=watchman
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - intranet
    expose:
      - "8084"
      - "9094"
networks:
  intranet: {}
